# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Video": "00_VideoCopy.ipynb",
         "YTVideo": "00_VideoCopy.ipynb",
         "parseCLI": "00_VideoCopy.ipynb"}

modules = ["VideoCopy.py"]

doc_url = "https://j-hunter.github.io/arkmedia/"

git_url = "https://github.com/j-hunter/arkmedia/tree/master/"

def custom_doc_links(name): return None
